[package]
name = "socks5-protocol-async"
version = "0.1.0"
authors = ["MOZGIII <mike-n@narod.ru>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.17"
failure = "0.1"
enum-primitive-derive = "0.1"
num-traits = "0.2"

[dev-dependencies]
futures-test-preview = "0.3.0-alpha.17"
